[2022-01-29 14:07:25,948] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:25,995] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:25,996] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:25,996] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:25,996] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:26,043] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-01-02 06:00:00+00:00
[2022-01-29 14:07:26,048] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-01-29 14:07:26,053] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmprb1c8rig', '--error-file', '/tmp/tmpsrptar2q']
[2022-01-29 14:07:26,054] {standard_task_runner.py:77} INFO - Job 17: Subtask get_data
[2022-01-29 14:07:26,284] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:26,601] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-01-29 14:07:26,603] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:26,620] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:26,639] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:26,643] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:26,643] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:26,897] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190102T060000, start_date=20220129T140725, end_date=20220129T140726
[2022-01-29 14:07:27,075] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:27,370] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:37:17,582] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-01-30 10:37:17,627] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-01-30 10:37:17,628] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:37:17,628] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:37:17,628] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:37:17,688] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-01-02 06:00:00+00:00
[2022-01-30 10:37:17,698] {standard_task_runner.py:52} INFO - Started process 257 to run task
[2022-01-30 10:37:17,704] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpti06y8_k', '--error-file', '/tmp/tmpc0fp8b4w']
[2022-01-30 10:37:17,705] {standard_task_runner.py:77} INFO - Job 62: Subtask get_data
[2022-01-30 10:37:18,017] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-01-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:37:18,224] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:37:18,322] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-01-30 10:37:18,325] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:37:18,327] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-01.csv > /opt/***output_2019-01.csv']
[2022-01-30 10:37:18,356] {subprocess.py:85} INFO - Output:
[2022-01-30 10:40:04,276] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:40:04,378] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190102T060000, start_date=20220130T103717, end_date=20220130T104004
[2022-01-30 10:40:04,461] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:40:04,552] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
