[2022-01-29 14:07:51,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:52,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:52,033] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:52,033] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:52,033] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:52,080] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-06-02 06:00:00+00:00
[2022-01-29 14:07:52,090] {standard_task_runner.py:52} INFO - Started process 370 to run task
[2022-01-29 14:07:52,096] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpwb2ezf38', '--error-file', '/tmp/tmp77nq2y1l']
[2022-01-29 14:07:52,096] {standard_task_runner.py:77} INFO - Job 35: Subtask get_data
[2022-01-29 14:07:52,287] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:52,505] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2022-01-29 14:07:52,507] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:52,508] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:52,521] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:52,525] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:52,525] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:52,586] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200602T060000, start_date=20220129T140751, end_date=20220129T140752
[2022-01-29 14:07:52,658] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:52,739] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:51:38,246] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2022-01-30 10:51:38,311] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2022-01-30 10:51:38,312] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:51:38,312] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:51:38,312] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:51:38,373] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-06-02 06:00:00+00:00
[2022-01-30 10:51:38,387] {standard_task_runner.py:52} INFO - Started process 960 to run task
[2022-01-30 10:51:38,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpo1gpkmcg', '--error-file', '/tmp/tmpk5en_hm_']
[2022-01-30 10:51:38,392] {standard_task_runner.py:77} INFO - Job 80: Subtask get_data
[2022-01-30 10:51:38,653] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-06-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:51:38,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:51:38,924] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2022-01-30 10:51:38,929] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:51:38,930] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-06.csv > /opt/***output_2020-06.csv']
[2022-01-30 10:51:38,947] {subprocess.py:85} INFO - Output:
[2022-01-30 10:51:48,096] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:51:48,217] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200602T060000, start_date=20220130T105138, end_date=20220130T105148
[2022-01-30 10:51:48,306] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:51:48,401] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
