[2022-01-29 14:07:56,491] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:56,558] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:56,559] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:56,559] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:56,559] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:56,625] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-09-02 06:00:00+00:00
[2022-01-29 14:07:56,635] {standard_task_runner.py:52} INFO - Started process 380 to run task
[2022-01-29 14:07:56,651] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-09-02T06:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp_cnpozeq', '--error-file', '/tmp/tmpcwvvanoc']
[2022-01-29 14:07:56,652] {standard_task_runner.py:77} INFO - Job 38: Subtask get_data
[2022-01-29 14:07:56,930] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:57,124] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-02T06:00:00+00:00
[2022-01-29 14:07:57,127] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:57,128] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:57,146] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:57,150] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:57,151] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:57,229] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200902T060000, start_date=20220129T140756, end_date=20220129T140757
[2022-01-29 14:07:57,312] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:57,400] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:52:02,386] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [queued]>
[2022-01-30 10:52:02,441] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [queued]>
[2022-01-30 10:52:02,441] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:52:02,442] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:52:02,442] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:52:02,497] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-09-02 06:00:00+00:00
[2022-01-30 10:52:02,504] {standard_task_runner.py:52} INFO - Started process 987 to run task
[2022-01-30 10:52:02,513] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-09-02T06:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpnmbazdpt', '--error-file', '/tmp/tmpquvi14_v']
[2022-01-30 10:52:02,513] {standard_task_runner.py:77} INFO - Job 83: Subtask get_data
[2022-01-30 10:52:02,670] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-09-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:52:02,798] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:52:02,847] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-02T06:00:00+00:00
[2022-01-30 10:52:02,849] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:52:02,850] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-09.csv > /opt/***output_2020-09.csv']
[2022-01-30 10:52:02,865] {subprocess.py:85} INFO - Output:
[2022-01-30 10:53:08,454] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:53:08,532] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200902T060000, start_date=20220130T105202, end_date=20220130T105308
[2022-01-30 10:53:08,624] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:53:08,723] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
