[2022-01-29 14:07:35,192] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:35,258] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:35,258] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:35,259] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:35,259] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:35,335] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-06-02 06:00:00+00:00
[2022-01-29 14:07:35,340] {standard_task_runner.py:52} INFO - Started process 321 to run task
[2022-01-29 14:07:35,348] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp14sfz8po', '--error-file', '/tmp/tmpys524bvd']
[2022-01-29 14:07:35,357] {standard_task_runner.py:77} INFO - Job 23: Subtask get_data
[2022-01-29 14:07:35,591] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:35,864] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-01-29 14:07:35,870] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:35,871] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:35,900] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:35,904] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:35,905] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:36,178] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190602T060000, start_date=20220129T140735, end_date=20220129T140736
[2022-01-29 14:07:36,290] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:36,385] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:40:29,268] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-01-30 10:40:29,321] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-01-30 10:40:29,322] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:40:29,322] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:40:29,323] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:40:29,386] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-06-02 06:00:00+00:00
[2022-01-30 10:40:29,393] {standard_task_runner.py:52} INFO - Started process 426 to run task
[2022-01-30 10:40:29,400] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp9y9l_k2i', '--error-file', '/tmp/tmpbgbulm7x']
[2022-01-30 10:40:29,401] {standard_task_runner.py:77} INFO - Job 67: Subtask get_data
[2022-01-30 10:40:29,596] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-06-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:40:29,786] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:40:29,844] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-01-30 10:40:29,847] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:40:29,849] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-06.csv > /opt/***output_2019-06.csv']
[2022-01-30 10:40:29,881] {subprocess.py:85} INFO - Output:
[2022-01-30 10:42:45,577] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:42:45,657] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190602T060000, start_date=20220130T104029, end_date=20220130T104245
[2022-01-30 10:42:45,714] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:42:45,806] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
