[2022-01-29 14:07:41,320] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:41,364] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:41,365] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:41,365] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:41,365] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:41,427] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-11-02 06:00:00+00:00
[2022-01-29 14:07:41,437] {standard_task_runner.py:52} INFO - Started process 344 to run task
[2022-01-29 14:07:41,445] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-11-02T06:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpc0iirk_j', '--error-file', '/tmp/tmpq_qdcyf3']
[2022-01-29 14:07:41,446] {standard_task_runner.py:77} INFO - Job 28: Subtask get_data
[2022-01-29 14:07:41,670] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:41,881] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-02T06:00:00+00:00
[2022-01-29 14:07:41,884] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:41,885] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:41,904] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:41,908] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:41,909] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:41,990] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20191102T060000, start_date=20220129T140741, end_date=20220129T140741
[2022-01-29 14:07:42,080] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:42,175] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:45:08,277] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-01-30 10:45:08,340] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-01-30 10:45:08,340] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:45:08,340] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:45:08,341] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:45:08,391] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-11-02 06:00:00+00:00
[2022-01-30 10:45:08,400] {standard_task_runner.py:52} INFO - Started process 646 to run task
[2022-01-30 10:45:08,407] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-11-02T06:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmplduguw_8', '--error-file', '/tmp/tmpnq35yxdf']
[2022-01-30 10:45:08,408] {standard_task_runner.py:77} INFO - Job 73: Subtask get_data
[2022-01-30 10:45:08,578] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-11-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:45:08,729] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:45:08,786] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-02T06:00:00+00:00
[2022-01-30 10:45:08,790] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:45:08,791] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-11.csv > /opt/***output_2019-11.csv']
[2022-01-30 10:45:08,808] {subprocess.py:85} INFO - Output:
[2022-01-30 10:48:26,306] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:48:26,381] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20191102T060000, start_date=20220130T104508, end_date=20220130T104826
[2022-01-30 10:48:26,460] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:48:26,569] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
