[2022-01-29 14:07:43,853] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:43,895] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:43,896] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:43,896] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:43,896] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:43,942] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-01-02 06:00:00+00:00
[2022-01-29 14:07:43,947] {standard_task_runner.py:52} INFO - Started process 349 to run task
[2022-01-29 14:07:43,954] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-01-02T06:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp_fwv5vhs', '--error-file', '/tmp/tmprdztw3qs']
[2022-01-29 14:07:43,955] {standard_task_runner.py:77} INFO - Job 30: Subtask get_data
[2022-01-29 14:07:44,121] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:44,289] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-02T06:00:00+00:00
[2022-01-29 14:07:44,292] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:44,294] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:44,310] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:44,314] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:44,314] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:44,381] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200102T060000, start_date=20220129T140743, end_date=20220129T140744
[2022-01-29 14:07:44,479] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:44,580] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:48:41,751] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-30 10:48:41,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-30 10:48:41,799] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:48:41,799] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:48:41,799] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:48:41,854] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-01-02 06:00:00+00:00
[2022-01-30 10:48:41,861] {standard_task_runner.py:52} INFO - Started process 813 to run task
[2022-01-30 10:48:41,867] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-01-02T06:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpas_g0k8y', '--error-file', '/tmp/tmp02cfxmk1']
[2022-01-30 10:48:41,868] {standard_task_runner.py:77} INFO - Job 75: Subtask get_data
[2022-01-30 10:48:42,062] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-01-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:48:42,211] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:48:42,277] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-02T06:00:00+00:00
[2022-01-30 10:48:42,280] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:48:42,282] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-01.csv > /opt/***output_2020-01.csv']
[2022-01-30 10:48:42,305] {subprocess.py:85} INFO - Output:
[2022-01-30 10:51:13,281] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:51:13,417] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200102T060000, start_date=20220130T104841, end_date=20220130T105113
[2022-01-30 10:51:13,518] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:51:13,683] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
