[2022-01-30 14:43:16,124] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-01-30 14:43:16,169] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-01-30 14:43:16,169] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 14:43:16,170] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-30 14:43:16,170] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 14:43:16,214] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2019-04-02 06:00:00+00:00
[2022-01-30 14:43:16,222] {standard_task_runner.py:52} INFO - Started process 459 to run task
[2022-01-30 14:43:16,229] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'csv_to_parquet', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpcvflv31m', '--error-file', '/tmp/tmpwipeyhfy']
[2022-01-30 14:43:16,231] {standard_task_runner.py:77} INFO - Job 191: Subtask csv_to_parquet
[2022-01-30 14:43:16,432] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [running]> on host 785c0c715caa
[2022-01-30 14:43:16,585] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 14:43:16,647] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-01-30 14:43:34,974] {python.py:175} INFO - Done. Returned value was: None
[2022-01-30 14:43:35,010] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=csv_to_parquet, execution_date=20190402T060000, start_date=20220130T144316, end_date=20220130T144335
[2022-01-30 14:43:35,405] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 14:43:35,553] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-02 11:21:49,945] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-02 11:21:49,982] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-02 11:21:49,983] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:21:49,983] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-02 11:21:49,983] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:21:50,025] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2019-04-02 06:00:00+00:00
[2022-02-02 11:21:50,033] {standard_task_runner.py:52} INFO - Started process 91 to run task
[2022-02-02 11:21:50,039] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'csv_to_parquet', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp3o_0duzt', '--error-file', '/tmp/tmpl_ngu06r']
[2022-02-02 11:21:50,041] {standard_task_runner.py:77} INFO - Job 305: Subtask csv_to_parquet
[2022-02-02 11:21:50,217] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [running]> on host 54c5cc6bfb2a
[2022-02-02 11:21:50,363] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 11:21:50,438] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-02-02 11:21:50,440] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_fhv.py", line 17, in fhv_csv_to_parquet
    table = pv.read_csv(srcfile)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflowoutput_2019-04.csv'. Detail: [errno 2] No such file or directory
[2022-02-02 11:21:50,480] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=HomeWorkWeek2, task_id=csv_to_parquet, execution_date=20190402T060000, start_date=20220202T112149, end_date=20220202T112150
[2022-02-02 11:21:50,531] {standard_task_runner.py:92} ERROR - Failed to execute job 305 for task csv_to_parquet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_fhv.py", line 17, in fhv_csv_to_parquet
    table = pv.read_csv(srcfile)
  File "pyarrow/_csv.pyx", line 862, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 755, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflowoutput_2019-04.csv'. Detail: [errno 2] No such file or directory
[2022-02-02 11:21:50,555] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-02 11:21:50,702] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-19 00:49:53,845] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 00:49:53,910] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 00:49:53,914] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 00:49:53,915] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 00:49:53,915] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 00:49:53,986] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2019-04-02 06:00:00+00:00
[2022-02-19 00:49:53,995] {standard_task_runner.py:52} INFO - Started process 937 to run task
[2022-02-19 00:49:54,002] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'csv_to_parquet', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpz2_w0z98', '--error-file', '/tmp/tmp4s_5dn1b']
[2022-02-19 00:49:54,004] {standard_task_runner.py:77} INFO - Job 530: Subtask csv_to_parquet
[2022-02-19 00:49:54,277] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [running]> on host 312f1fe573aa
[2022-02-19 00:49:54,488] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 00:49:54,611] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-02-19 00:50:24,131] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 00:50:24,182] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=csv_to_parquet, execution_date=20190402T060000, start_date=20220219T004953, end_date=20220219T005024
[2022-02-19 00:50:24,527] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 00:50:24,659] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-19 10:54:25,532] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 10:54:25,579] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 10:54:25,579] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 10:54:25,580] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 10:54:25,580] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 10:54:25,652] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2019-04-02 06:00:00+00:00
[2022-02-19 10:54:25,663] {standard_task_runner.py:52} INFO - Started process 2026 to run task
[2022-02-19 10:54:25,670] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'csv_to_parquet', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '900', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpnbxnpshw', '--error-file', '/tmp/tmppyfjvbis']
[2022-02-19 10:54:25,672] {standard_task_runner.py:77} INFO - Job 900: Subtask csv_to_parquet
[2022-02-19 10:54:25,953] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [running]> on host f81f14254480
[2022-02-19 10:54:26,135] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 10:54:26,195] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-02-19 10:55:16,389] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 10:55:16,427] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=csv_to_parquet, execution_date=20190402T060000, start_date=20220219T105425, end_date=20220219T105516
[2022-02-19 10:55:16,826] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 10:55:17,285] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-19 23:38:01,738] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 23:38:01,785] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-02-19 23:38:01,786] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:38:01,786] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 23:38:01,787] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:38:01,854] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2019-04-02 06:00:00+00:00
[2022-02-19 23:38:01,864] {standard_task_runner.py:52} INFO - Started process 22001 to run task
[2022-02-19 23:38:01,871] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'csv_to_parquet', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '1063', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpetlrw766', '--error-file', '/tmp/tmp55ewyv3q']
[2022-02-19 23:38:01,873] {standard_task_runner.py:77} INFO - Job 1063: Subtask csv_to_parquet
[2022-02-19 23:38:02,121] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.csv_to_parquet scheduled__2019-04-02T06:00:00+00:00 [running]> on host d9977d7db207
[2022-02-19 23:38:02,355] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 23:38:02,441] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-02-19 23:38:26,892] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 23:38:26,957] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=csv_to_parquet, execution_date=20190402T060000, start_date=20220219T233801, end_date=20220219T233826
[2022-02-19 23:38:27,321] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 23:38:27,478] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
