[2022-01-29 14:07:39,805] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:39,849] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:39,849] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:39,850] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:39,850] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:39,924] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-09-02 06:00:00+00:00
[2022-01-29 14:07:39,931] {standard_task_runner.py:52} INFO - Started process 337 to run task
[2022-01-29 14:07:39,946] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpjie26ebk', '--error-file', '/tmp/tmpegu16qi8']
[2022-01-29 14:07:39,947] {standard_task_runner.py:77} INFO - Job 26: Subtask get_data
[2022-01-29 14:07:40,255] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:40,542] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-01-29 14:07:40,544] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:40,546] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:40,569] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:40,570] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:40,570] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:40,736] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190902T060000, start_date=20220129T140739, end_date=20220129T140740
[2022-01-29 14:07:40,852] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:40,988] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:44:38,875] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-01-30 10:44:38,951] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2022-01-30 10:44:38,952] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:44:38,952] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:44:38,952] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:44:39,003] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-09-02 06:00:00+00:00
[2022-01-30 10:44:39,014] {standard_task_runner.py:52} INFO - Started process 622 to run task
[2022-01-30 10:44:39,021] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpkx4lw34p', '--error-file', '/tmp/tmpq9glbdvb']
[2022-01-30 10:44:39,022] {standard_task_runner.py:77} INFO - Job 71: Subtask get_data
[2022-01-30 10:44:39,239] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-09-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:44:39,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:44:39,562] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2022-01-30 10:44:39,565] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:44:39,567] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-09.csv > /opt/***output_2019-09.csv']
[2022-01-30 10:44:39,588] {subprocess.py:85} INFO - Output:
[2022-01-30 10:49:06,041] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:49:06,125] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190902T060000, start_date=20220130T104438, end_date=20220130T104906
[2022-01-30 10:49:06,197] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:49:06,298] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
