[2022-01-29 14:07:25,948] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data manual__2022-01-29T14:07:24.129412+00:00 [queued]>
[2022-01-29 14:07:25,994] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data manual__2022-01-29T14:07:24.129412+00:00 [queued]>
[2022-01-29 14:07:25,995] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:25,995] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:25,995] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:26,049] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2022-01-29 14:07:24.129412+00:00
[2022-01-29 14:07:26,054] {standard_task_runner.py:52} INFO - Started process 296 to run task
[2022-01-29 14:07:26,062] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'manual__2022-01-29T14:07:24.129412+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpmw03f7kg', '--error-file', '/tmp/tmptvj8pcvm']
[2022-01-29 14:07:26,063] {standard_task_runner.py:77} INFO - Job 18: Subtask get_data
[2022-01-29 14:07:26,350] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data manual__2022-01-29T14:07:24.129412+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:26,678] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-29T14:07:24.129412+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-29T14:07:24.129412+00:00
[2022-01-29 14:07:26,680] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:26,681] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:26,699] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:26,704] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:26,705] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:26,900] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20220129T140724, start_date=20220129T140725, end_date=20220129T140726
[2022-01-29 14:07:27,058] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:27,437] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
