[2022-01-29 14:07:57,206] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:57,258] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:57,258] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:57,258] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:57,258] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:57,312] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-10-02 06:00:00+00:00
[2022-01-29 14:07:57,317] {standard_task_runner.py:52} INFO - Started process 383 to run task
[2022-01-29 14:07:57,324] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-10-02T06:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpmysgjqrh', '--error-file', '/tmp/tmps8t8nfln']
[2022-01-29 14:07:57,325] {standard_task_runner.py:77} INFO - Job 39: Subtask get_data
[2022-01-29 14:07:57,497] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:57,702] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-10-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-02T06:00:00+00:00
[2022-01-29 14:07:57,704] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:57,705] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:57,719] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:57,722] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:57,723] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:57,793] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20201002T060000, start_date=20220129T140757, end_date=20220129T140757
[2022-01-29 14:07:57,868] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:57,985] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:52:13,878] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [queued]>
[2022-01-30 10:52:13,933] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [queued]>
[2022-01-30 10:52:13,934] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:52:13,934] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:52:13,934] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:52:13,988] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-10-02 06:00:00+00:00
[2022-01-30 10:52:14,000] {standard_task_runner.py:52} INFO - Started process 1001 to run task
[2022-01-30 10:52:14,008] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-10-02T06:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpulpzeefo', '--error-file', '/tmp/tmpl0lolyo7']
[2022-01-30 10:52:14,009] {standard_task_runner.py:77} INFO - Job 84: Subtask get_data
[2022-01-30 10:52:14,278] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-10-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:52:14,480] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:52:14,556] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-10-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-02T06:00:00+00:00
[2022-01-30 10:52:14,560] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:52:14,561] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-10.csv > /opt/***output_2020-10.csv']
[2022-01-30 10:52:14,586] {subprocess.py:85} INFO - Output:
[2022-01-30 10:52:31,858] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:52:31,959] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20201002T060000, start_date=20220130T105213, end_date=20220130T105231
[2022-01-30 10:52:32,054] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:52:32,167] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
