[2022-01-29 14:07:27,378] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:27,590] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:27,591] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:27,617] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:27,617] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:27,858] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-02-02 06:00:00+00:00
[2022-01-29 14:07:27,875] {standard_task_runner.py:52} INFO - Started process 301 to run task
[2022-01-29 14:07:27,883] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpq4q0bbon', '--error-file', '/tmp/tmpi791fr3r']
[2022-01-29 14:07:27,884] {standard_task_runner.py:77} INFO - Job 19: Subtask get_data
[2022-01-29 14:07:28,199] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:29,104] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-01-29 14:07:29,106] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:29,140] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:29,189] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:29,195] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:29,196] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:29,380] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190202T060000, start_date=20220129T140727, end_date=20220129T140729
[2022-01-29 14:07:29,568] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:30,164] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:37:18,417] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-01-30 10:37:18,467] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-01-30 10:37:18,467] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:37:18,467] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:37:18,468] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:37:18,529] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2019-02-02 06:00:00+00:00
[2022-01-30 10:37:18,543] {standard_task_runner.py:52} INFO - Started process 272 to run task
[2022-01-30 10:37:18,552] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp7vwx50hu', '--error-file', '/tmp/tmprf_9tq2k']
[2022-01-30 10:37:18,553] {standard_task_runner.py:77} INFO - Job 63: Subtask get_data
[2022-01-30 10:37:18,764] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2019-02-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:37:18,880] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:37:18,929] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-01-30 10:37:18,932] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:37:18,935] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-02.csv > /opt/***output_2019-02.csv']
[2022-01-30 10:37:18,959] {subprocess.py:85} INFO - Output:
[2022-01-30 10:39:39,040] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:39:39,140] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20190202T060000, start_date=20220130T103718, end_date=20220130T103939
[2022-01-30 10:39:39,196] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:39:39,317] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
